CACHE MANIFEST
CACHE:
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/css/bootstrap.css
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/css/effeckt.css
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/css/foundation.css
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/css/kontext.css
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/css/monstrofront.css
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/css/monstro-widgets.css
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/css/monstrotheme-customizable-frontend.css
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/css/monstrotheme-frontend.css
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/css/normalize.css
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/fonts/glyphicons-halflings-regular.eot
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/fonts/glyphicons-halflings-regular.svg
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/fonts/glyphicons-halflings-regular.ttf
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/fonts/glyphicons-halflings-regular.woff
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/fonts/monstrofront.eot
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/fonts/monstrofront.svg
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/fonts/monstrofront.ttf
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/fonts/monstrofront.woff
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/js/angular.js
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/js/angular-animate.js
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/js/angular-route.js
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/js/angular-sanitize.js
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/js/monstro-directives.js
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/js/monstrotheme-customizable-frontend.js
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/js/monstrotheme-frontend.js
http://localhost/wordpress/gagarin/wp-content/themes/Gagarin/js/ngStorage.js
NETWORK:
*
<?php
exit;